##############################################################
### Para crear de los recursos, ejecutar 'helm template .' ###
##############################################################


# Global
namespace: poc-clh
name: app01

### DeploymentConfig ###
deploymentConfig:
  - name: dc01
    labels:
      environment: dev
      team: dev
      app: app01
    annotations:
      description: "Annotations de mi app01 ambiente dev"
      createdBy: "RedHat"
    replicas: 2  
    container:
      ports:
        - 80
        - 8080
      imageStream: is01
      imageTag: latest

  - name: dc02
    labels:
      environment: dev
      team: dev
      app: app02
    annotations:
      description: "Annotations de mi app02 ambiente dev"
      createdBy: "RedHat"
    replicas: 1 
    container:
      ports:
        - 8080
      imageStream: is02
      imageTag: v1


### Services ###
service:
  - name: dc01
    ports:
      - 80
      - 8080
    #route_name:   
  - name: dc02
    ports:
      - 8080
    #route_name:  


### ImageStreams ###
imageStream:
  - name: is01
    tags:
      - tag: latest
        image: docker.io/vitokotoko20/flask:latest

    

  - name: is02
    tags:
      - tag: v1
        image: docker.io/vitokotoko20/flask:latest

        
### ConfigMap ###
configMaps:
  - name: configmap1
    envVars:
      envVar1: "value1"
      envVar2: "value2"
      envVar3: "value3"
  - name: configmap2
    envVars:
      envVar1: "value3"
      envVar2: "value4"
