# templates/configmap.yml
#{{- $root := . -}}
{{- if .Values.configMaps }}
{{- range $configMap := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMap.name }}
  namespace: {{ $.Values.namespace }}
data:
{{- range $key, $value := $configMap.envVars }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
#{{- end }}